In [1]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_csv('data/monthlyData_updated.csv')
#data = data.drop('Unnamed: 0', axis = 1)

# Exclude the columns that have any missing values
data = data.dropna(axis=1, how='any')
data['L0_HOUST'] = data['L0_HOUST'].diff()
data = data.dropna().reset_index(drop = True)
# Rename a column
data = data.rename(columns = {'Unnamed: 0': 'Date'})

x_d_all = data[['Date', 'L0_OILPRICEx', 'L0_EXUSUKx', 'L0_S.P.500', 'L0_TB3MS', 'L_0y', 'L0_UNRATE', 'L0_HOUST']]
x_d_all.columns = ['Date', 'oil', 'Ex', 'SPY', 'DGS3', 'inf', 'unrate', 'house_starts']

In [11]:
x_d_all.to_csv('SVol Benchmarks/monthlyData_updated.csv')

In [12]:
data = pd.read_csv('data/quarterlyData_updated.csv')
#data = data.drop('Unnamed: 0', axis = 1)
# No need to difference the housing data
data = data.rename(columns = {'Unnamed: 0': 'Date'})

x_d_all = data[['Date', 'L0_OILPRICEx', 'L0_EXUSUKx', 'L0_S.P.500', 'L0_TB3MS', 'L0_GDPC1', 'L_0y', 'L0_UNRATE', 'L0_HOUST']]
x_d_all.columns = ['Date', 'oil', 'Ex', 'SPY', 'DGS3', 'GDP', 'inf', 'unrate', 'house_starts']

In [13]:
x_d_all.to_csv('SVol Benchmarks/quarterlyData_updated.csv')

In [14]:
x_d_all

,Date,oil,Ex,SPY,DGS3,GDP,inf,unrate,house_starts
0,6/1/1960,-0.003153,0.000178,-0.026073,-0.3567,0.022228,0.000909,-0.4667,-0.071086
1,9/1/1960,-0.003786,0.001105,-0.003680,-0.8800,-0.005405,0.005990,0.1000,-0.067293
2,12/1/1960,-0.003927,0.001531,-0.006262,-0.6333,0.004882,0.000565,0.3000,-0.045407
3,3/1/1961,-0.003252,0.000178,-0.006964,-0.0533,-0.012917,0.006401,0.7334,-0.023079
4,6/1/1961,-0.001703,-0.003421,0.113813,0.0433,0.006726,0.002013,0.5333,0.045637
...,...,...,...,...,...,...,...,...,...
244,6/1/2021,0.301790,0.043424,0.083164,-0.0433,0.015222,0.010090,-0.5667,0.004437
245,9/1/2021,0.119256,0.014042,0.079580,-0.0233,0.016274,0.019673,-0.3000,0.006515
246,12/1/2021,0.055409,-0.014840,0.055490,0.0200,0.005693,0.016250,-0.8000,-0.013921
247,3/1/2022,0.080207,-0.021271,0.039864,0.0066,0.016668,0.019037,-0.8667,0.067547
248,6/1/2022,0.185383,-0.005054,-0.029542,0.2534,-0.003965,0.022005,-0.4333,0.023932